version: '3'
services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test5
    ports:
      - "3306:3306"
    expose:
      - "3306"
  web-service:
    build: .
    ports:
      - "80:80"
    depends_on:
      - docker-mysql