version: '3'
services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test5
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
  web-service:
    build: .
    ports:
      - "80:80"
    depends_on:
      - docker-mysql