spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      order_inserts: true
      order_updatest: true
      jdbc:
        batch_size: 4
    generate-ddl: true
    show-sql: true
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://docker-mysql:3306/test5?autoReconnect=true&useSSL=false
    username: root
    password: root
